"""Generate nao_config.yaml and RULES.md for the Nao analytics agent.

Nao (https://getnao.io) is a local AI analytics agent that connects to a
DuckDB warehouse and a dbt project, letting users query data in natural
language. This module generates its config from tycoon.yml so the user
never has to write nao_config.yaml by hand.
"""

from __future__ import annotations

import os
from pathlib import Path

import yaml

from tycoon.config import TycoonConfig

# Directories `nao sync` walks unconditionally — pre-creating them prevents
# the "No such file or directory: 'repos'" / 'databases' / etc. crashes
# called out in issue #7. Nao writes into these as it discovers content.
_NAO_REQUIRED_DIRS = (
    "databases",
    "queries",
    "docs",
    "semantics",
    "repos",
    "agent/tools",
    "agent/mcps",
    "agent/skills",
)

# Files Nao writes into the synced trees that are PII-bearing or large.
# Auto-generated .gitignore inside .tycoon/nao/ so users don't accidentally
# commit row previews / synced dbt repos / chat databases (issue #7 §7).
_NAO_GITIGNORE = """\
# Auto-generated by tycoon ask — do not edit
# These directories carry PII (row previews) or large machine-state.
databases/
repos/
db.sqlite*
"""

# LM Studio's default OpenAI-compatible endpoint. Stable across the
# product. The api_key field is literally ignored by LM Studio — we still
# set a placeholder so Nao's request library doesn't bail out on a
# missing key.
_LM_STUDIO_PRESET = {
    "provider": "openai",
    "base_url": "http://localhost:1234/v1",
    "api_key": "lm-studio",
}

# Ollama's OpenAI-compatible endpoint (added in Ollama 0.1.27+). Same
# api_key-is-ignored story as LM Studio.
_OLLAMA_PRESET = {
    "provider": "openai",
    "base_url": "http://localhost:11434/v1",
    "api_key": "ollama",
}

_DEFAULT_RULES_TEMPLATE = """\
You are an analytics assistant for the {name} project.

- Always explain your SQL and the business logic behind it clearly.
- Prefer mart tables over staging tables when answering business questions.
- When results are empty, suggest why that might be and what to check.
"""

AGENTS_MD_SENTINEL = "<!-- @generated by tycoon ask -->"

_AGENTS_MD_TEMPLATE = """\
{sentinel}
<!-- Regenerated by `tycoon register llm` and `tycoon ask sync`.
     Delete this sentinel line to take ownership; tycoon will then
     leave AGENTS.md alone on subsequent syncs. -->

# {project_name}

This is a [tycoon](https://github.com/Database-Tycoon/tycoon-cli)-managed
analytics project. Coding agents working in this repository should consult
the auto-synced context under `.tycoon/nao/` to understand the data and
dbt models.

## Database context

`.tycoon/nao/databases/type=<engine>/database=<name>/schema=<schema>/table=<table>/`
contains, for every table the warehouse exposes:

- `columns.md` — column names + types
- `preview.md` — sample rows

Read the matching folder when asked about a specific table.

## dbt project (synced copy)

`.tycoon/nao/repos/dbt/models/` is a synced copy of the project's dbt
models, sources, and schema YAML. Use it to trace lineage and read SQL
without needing the live warehouse.

## Project rules

`.tycoon/nao/RULES.md` carries project-specific guidance (preferred
tables, naming conventions, business logic). Apply it when answering
data questions.

## Pipe context to any agent

```bash
tycoon ask context --table <table>      # cat columns.md + preview.md
tycoon ask context --schema <schema>    # all tables in a schema
tycoon ask context --rules-only         # just RULES.md
tycoon ask context                      # list available context
```

## Refreshing the context

Run `tycoon ask sync` after meaningful warehouse or dbt changes; the
files above will be regenerated. `tycoon ask chat` launches the Nao web
UI on the same context.
"""


def _rel(from_dir: Path, to_path: Path) -> str:
    """Return a relative path string from from_dir to to_path."""
    return str(os.path.relpath(to_path, from_dir))


def _warehouse_path_for_nao(cfg: TycoonConfig) -> str:
    """Return the database connection string for Nao's ``path`` field.

    MotherDuck URLs (``md:<catalog>``) are passed through verbatim — DuckDB
    and Ibis both accept them as connection arguments. Local DuckDB paths
    are turned into a path relative to ``.tycoon/nao/`` so nao can resolve
    them from its own working directory.
    """
    project = cfg.project
    raw = project.database.warehouse if project else ""
    if raw.startswith("md:"):
        return raw
    return _rel(cfg.nao_dir, cfg.local_db)


def _expand_schema_globs(names: list[str]) -> list[str]:
    """Turn bare schema names into ``<schema>.*`` globs for Nao's
    ``fnmatch``-on-``schema.table`` filter. Leaves already-qualified
    patterns (anything containing ``.``, ``*``, or ``?``) untouched."""
    out: list[str] = []
    for n in names:
        if any(c in n for c in ".*?"):
            out.append(n)
        else:
            out.append(f"{n}.*")
    return out


def build_nao_config(cfg: TycoonConfig) -> dict:
    """Build the nao_config.yaml dict from tycoon config."""
    project = cfg.project
    nao_dir = cfg.nao_dir
    ask = project.ask if project else None

    # Database entry pointing at the warehouse DuckDB
    db_entry: dict = {
        "name": project.name if project else "tycoon-warehouse",
        "type": "duckdb",
        "path": _warehouse_path_for_nao(cfg),
        # Nao 0.1.x renamed `accessors` → `templates`. Older versions (< 0.1.0)
        # won't see this key; that's fine — our [ask] extra pins >= 0.1.7.
        "templates": ["columns", "preview"],
        "profiling": {
            "refresh_policy": "interval",
            "interval_days": 1,
        },
    }
    if ask and ask.include_schemas:
        db_entry["include"] = _expand_schema_globs(ask.include_schemas)
    if ask and ask.exclude_schemas:
        db_entry["exclude"] = _expand_schema_globs(ask.exclude_schemas)

    # Repo entry pointing at the dbt project
    repo_entry = {
        "name": "dbt",
        "local_path": _rel(nao_dir, cfg.dbt_project_dir),
        "include": ["models/**/*.sql", "models/**/*.yml"],
    }

    config: dict = {
        "project_name": project.name if project else "tycoon",
        "databases": [db_entry],
        "repos": [repo_entry],
    }

    # LLM config
    if ask and ask.llm:
        llm = ask.llm
        # `lm-studio` is a tycoon shortcut: expand to OpenAI-compatible
        # config pointed at LM Studio's default :1234/v1 endpoint. Issue
        # #7 §5 — make LM Studio a first-class option without making
        # users discover that "openai + custom base_url" is the path.
        if llm.provider == "lm-studio":
            llm_entry: dict = dict(_LM_STUDIO_PRESET)
            if llm.base_url:
                llm_entry["base_url"] = llm.base_url
            if llm.model:
                llm_entry["model"] = llm.model
        elif llm.provider == "ollama":
            llm_entry = dict(_OLLAMA_PRESET)
            if llm.base_url:
                llm_entry["base_url"] = llm.base_url
            if llm.model:
                llm_entry["model"] = llm.model
        else:
            llm_entry = {"provider": llm.provider}
            if llm.model:
                llm_entry["model"] = llm.model
            if llm.base_url:
                llm_entry["base_url"] = llm.base_url
            if llm.api_key_env:
                # Use nao's {{ env('VAR') }} interpolation — NOT tycoon's ${VAR}
                llm_entry["api_key"] = f"{{{{ env('{llm.api_key_env}') }}}}"
        config["llm"] = llm_entry

    # Skills config
    skills_dir = Path(ask.skills_dir) if (ask and ask.skills_dir) else nao_dir / "agent" / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)
    config["skills"] = {
        "folder_path": str(skills_dir)
    }

    # MCP config
    mcp_path = nao_dir / "agent" / "mcps" / "mcp.json"
    mcp_path.parent.mkdir(parents=True, exist_ok=True)
    if not mcp_path.exists():
        mcp_path.write_text('{"mcpServers": {}}')
    config["mcp"] = {"json_file_path": str(mcp_path)}

    return config


def build_rules(cfg: TycoonConfig) -> str:
    """Return the RULES.md content."""
    project = cfg.project
    ask = project.ask if project else None
    if ask and ask.rules:
        return ask.rules
    name = project.name if project else "tycoon"
    return _DEFAULT_RULES_TEMPLATE.format(name=name)


def build_agents_md(cfg: TycoonConfig) -> str:
    """Return the generated AGENTS.md body that points at the nao context tree."""
    project = cfg.project
    name = project.name if project else "tycoon"
    return _AGENTS_MD_TEMPLATE.format(sentinel=AGENTS_MD_SENTINEL, project_name=name)


def write_agents_md(cfg: TycoonConfig) -> tuple[bool, Path]:
    """Write AGENTS.md at the project root.

    Idempotent and respectful of user-authored files: if an AGENTS.md
    exists without the tycoon sentinel in its first 500 chars, leave it
    alone and return (False, path) so callers can warn the user.
    """
    target = cfg.root / "AGENTS.md"
    if target.exists():
        head = target.read_text(errors="replace")[:500]
        if AGENTS_MD_SENTINEL not in head:
            return False, target
    target.write_text(build_agents_md(cfg))
    return True, target


def ensure_nao_dirs(nao_dir: Path) -> None:
    """Pre-create every directory ``nao sync`` walks unconditionally.

    Issue #7 §4: ``nao sync`` crashes with ``No such file or directory:
    'repos'`` / ``'databases'`` / etc. unless the eight directories below
    exist. ``tycoon register llm`` should always leave Nao able to run
    immediately afterward without a separate ``nao init`` step.
    """
    for sub in _NAO_REQUIRED_DIRS:
        (nao_dir / sub).mkdir(parents=True, exist_ok=True)


def write_nao_gitignore(nao_dir: Path) -> None:
    """Write ``.tycoon/nao/.gitignore`` to keep PII previews + big sync
    artifacts out of version control. Issue #7 §7.

    Idempotent: only writes if the file is missing or matches our
    auto-generated content. A user-authored .gitignore is left alone.
    """
    target = nao_dir / ".gitignore"
    if target.exists():
        existing = target.read_text(errors="replace")
        if "Auto-generated by tycoon ask" not in existing:
            return  # user-authored, leave alone
    target.write_text(_NAO_GITIGNORE)


def write_nao_project(cfg: TycoonConfig) -> None:
    """Write nao_config.yaml, RULES.md, .gitignore, and pre-created dirs to .tycoon/nao/."""
    nao_dir = cfg.nao_dir
    nao_dir.mkdir(parents=True, exist_ok=True)
    ensure_nao_dirs(nao_dir)
    write_nao_gitignore(nao_dir)

    config = build_nao_config(cfg)
    config_path = nao_dir / "nao_config.yaml"
    config_path.write_text(yaml.dump(config, default_flow_style=False, sort_keys=False))

    rules_path = nao_dir / "RULES.md"
    rules_path.write_text(build_rules(cfg))
