"""Scaffold dbt staging models that expose tycoon's observability metadata.

Implements issue #20. Tycoon already accumulates rich metadata in
``.tycoon/metadata.duckdb`` (dlt runs, dlt traces, dbt invocations, dbt
nodes, manifest snapshots, schema-diff history). The Rill dashboards see
it via Parquet exports; this module makes the same data visible to dbt.

Three pieces compose:

1. **ATTACH** — every scaffolded dbt profile gains a third attached
   database (``tycoon_meta``) pointing at ``.tycoon/metadata.duckdb``,
   ``READ_ONLY``. dbt models can then ``SELECT * FROM
   tycoon_meta.main.dlt_runs`` directly.

2. **Staging models** — one ``stg_tycoon__<table>.sql`` view per
   metadata table, plus a unified ``dim_runs`` mart that unions dlt +
   dbt runs into one timeline. All ``materialized: view`` so they don't
   double-store data.

3. **Schema YAML** — ``_tycoon__schema.yml`` documents every column so
   ``dbt docs`` renders proper lineage.

Once the staging models exist they're part of the warehouse like any
other model — that's the third sub-ask in #20, satisfied emergently.
"""

from __future__ import annotations

import os
from pathlib import Path

import yaml


# Each tuple: (table_name_in_metadata_db, dbt_model_filename_stem, description)
# Tracks the schema documented in `docs/reference/observability.md`. Add new
# tables here when observability captures new state.
_METADATA_TABLES = [
    ("dlt_runs", "stg_tycoon__dlt_runs", "One row per dlt load — load_id, schema, status, inserted_at."),
    ("dlt_rows_by_table", "stg_tycoon__dlt_rows_by_table", "Per-table row counts within each dlt load."),
    ("dlt_trace_runs", "stg_tycoon__dlt_trace_runs", "Per-pipeline timing and success metadata from dlt's trace.pickle."),
    ("dlt_trace_steps", "stg_tycoon__dlt_trace_steps", "Per-step (extract / normalize / load) durations within a dlt run."),
    ("dlt_trace_jobs", "stg_tycoon__dlt_trace_jobs", "Per-job byte sizes and elapsed times from dlt's trace.pickle."),
    ("dbt_runs", "stg_tycoon__dbt_runs", "One row per dbt invocation — command, target, duration, success counts."),
    ("dbt_nodes", "stg_tycoon__dbt_nodes", "One row per (model, test, snapshot) per dbt invocation."),
    ("dbt_manifest_snapshots", "stg_tycoon__dbt_manifest_snapshots", "Per-invocation fingerprint of dbt's manifest.json."),
    ("dbt_schema_changes", "stg_tycoon__dbt_schema_changes", "Per-column / per-model changes detected across consecutive manifest snapshots."),
]

_DIM_RUNS_SQL = """\
{{ config(materialized='view', tags=['tycoon']) }}

-- Unified timeline of dlt + dbt runs.
-- Useful for "show me everything that's run today" / "what was the last
-- thing to fail" / freshness SLAs across the full pipeline.
--
-- Column names match the underlying observability schema (see
-- docs/reference/observability.md): dlt uses `inserted_at`, dbt uses
-- `started_at`; dbt has `elapsed_s` in seconds (dlt doesn't expose a
-- per-load duration in the captured rows). Pads with NULL where one
-- tool doesn't have an analog.

SELECT
    'dlt'                       AS tool,
    load_id                     AS run_id,
    source_schema               AS subject,
    inserted_at                 AS run_at,
    CAST(status AS VARCHAR)     AS status,
    NULL::DOUBLE                AS duration_seconds,
    NULL::VARCHAR               AS target_name
FROM {{ ref('stg_tycoon__dlt_runs') }}

UNION ALL BY NAME

SELECT
    'dbt'                       AS tool,
    invocation_id               AS run_id,
    command                     AS subject,
    started_at                  AS run_at,
    CASE WHEN success THEN 'ok' ELSE 'error' END AS status,
    elapsed_s                   AS duration_seconds,
    target_name                 AS target_name
FROM {{ ref('stg_tycoon__dbt_runs') }}
"""

_SCHEMA_YML_HEADER = """\
# Auto-generated by `tycoon data observability scaffold` — do not hand-edit.
# Re-run the scaffold command to refresh this file when the metadata schema
# evolves. Source of truth: docs/reference/observability.md.

version: 2

models:
"""


def _staging_sql(table_name: str) -> str:
    """SQL body for a stg_tycoon__<table>.sql view."""
    return f"""\
-- Auto-generated by `tycoon data observability scaffold` — do not hand-edit.
-- Source: tycoon's observability metadata DB (`.tycoon/metadata.duckdb`),
-- attached as `tycoon_meta` in this project's profiles.yml.

{{{{ config(materialized='view', tags=['tycoon']) }}}}

SELECT *
FROM tycoon_meta.main.{table_name}
"""


def _schema_yml(tables: list[tuple[str, str, str]]) -> str:
    """Build the _tycoon__schema.yml content for the staging models."""
    models = []
    for table_name, model_name, description in tables:
        models.append(
            {
                "name": model_name,
                "description": description,
                "config": {"materialized": "view"},
            }
        )
    models.append(
        {
            "name": "dim_runs",
            "description": (
                "Unified timeline of dlt + dbt runs. Combines stg_tycoon__dlt_runs "
                "and stg_tycoon__dbt_runs into a single tool-tagged view."
            ),
            "config": {"materialized": "view"},
        }
    )
    return _SCHEMA_YML_HEADER + yaml.dump(
        {"models": models}, default_flow_style=False, sort_keys=False
    ).split("models:\n", 1)[1]


def scaffold_observability_models(
    dbt_project_dir: Path,
) -> list[Path]:
    """Generate stg_tycoon__*.sql + dim_runs.sql + _tycoon__schema.yml.

    Idempotent: re-running overwrites the auto-generated files. User-authored
    files in the same directory aren't touched.

    Returns the list of files written.
    """
    target = dbt_project_dir / "models" / "_tycoon"
    target.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for table_name, model_name, _description in _METADATA_TABLES:
        path = target / f"{model_name}.sql"
        path.write_text(_staging_sql(table_name))
        written.append(path)

    dim_path = target / "dim_runs.sql"
    dim_path.write_text(_DIM_RUNS_SQL)
    written.append(dim_path)

    schema_path = target / "_tycoon__schema.yml"
    schema_path.write_text(_schema_yml(_METADATA_TABLES))
    written.append(schema_path)

    return written


def attach_metadata_to_profiles(
    profiles_yml_path: Path,
    metadata_db_path: Path,
) -> bool:
    """Add a `tycoon_meta` ATTACH entry to every output in ``profiles.yml``.

    Idempotent: skips outputs that already have a ``tycoon_meta`` attach.
    Returns True if any change was made, False if all outputs already had
    the attach.

    The path written is **relative to the dbt project root** (where dbt
    resolves attach paths from), which is also where ``profiles.yml``
    lives by convention.

    Ensures ``metadata.duckdb`` exists (empty schema) before writing the
    ATTACH so the very next ``dbt run`` doesn't fail on a missing file —
    even if no dlt or dbt run has fired yet.
    """
    from tycoon.observability import ensure_schema

    if not profiles_yml_path.exists():
        raise FileNotFoundError(f"profiles.yml not found: {profiles_yml_path}")

    # Pre-create the metadata DB with the empty observability schema.
    # Idempotent — re-running is a no-op if the schema already exists.
    ensure_schema(metadata_db_path)

    raw = yaml.safe_load(profiles_yml_path.read_text()) or {}
    if not isinstance(raw, dict):
        raise ValueError(f"profiles.yml is not a YAML mapping: {profiles_yml_path}")

    # Compute the path relative to the dbt project (profile siblings live there).
    dbt_dir = profiles_yml_path.parent
    metadata_abs = metadata_db_path.resolve()
    metadata_rel = os.path.relpath(metadata_abs, start=dbt_dir)

    changed = False
    for _profile_name, profile_data in raw.items():
        if not isinstance(profile_data, dict):
            continue
        outputs = profile_data.get("outputs", {})
        if not isinstance(outputs, dict):
            continue
        for _output_name, output_data in outputs.items():
            if not isinstance(output_data, dict):
                continue
            if output_data.get("type") != "duckdb":
                continue  # tycoon_meta is a DuckDB file; only relevant to duckdb outputs

            attach_list = output_data.setdefault("attach", [])
            if not isinstance(attach_list, list):
                continue
            already = any(
                isinstance(item, dict) and item.get("alias") == "tycoon_meta"
                for item in attach_list
            )
            if already:
                continue
            attach_list.append(
                {
                    "path": metadata_rel,
                    "alias": "tycoon_meta",
                    "read_only": True,
                }
            )
            changed = True

    if changed:
        profiles_yml_path.write_text(
            yaml.dump(raw, default_flow_style=False, sort_keys=False)
        )
    return changed
