"""Generate Open Semantic Interchange (OSI) v0.1.1 YAML from dbt marts.

OSI is a vendor-neutral semantic-layer format. Tycoon emits a portable
*view* on top of the user's dbt marts so downstream consumers (Snowflake
Cortex, ThoughtSpot, RelationalAI, ...) can consume metric definitions
without bespoke per-tool integration. dbt MetricFlow stays the source of
truth — the OSI file is regenerable.

## Conservative dial

Per the v0.1.6 design (issue #28, Q3): we scaffold *datasets* and
*fields*, but **not metrics**. OSI metrics are SQL expressions like
``SUM(orders.amount)`` — tycoon can't reasonably guess which sums,
distinct-counts, or ratios the user actually wants. Emitting an empty
metric list keeps the scaffold useful (full datasets + dimensions)
without polluting the file with bad guesses.

Numeric columns get fields *without* a ``dimension`` attribute (so
they're available for use in user-defined metric expressions). Strings,
dates, foreign-key-shaped columns, and booleans get ``dimension: {}``
(or ``dimension: {is_time: true}`` for timestamps).

## What gets included

- Tables matching ``mart_*`` / ``fct_*`` / ``dim_*`` / ``obt_*``.
- Tables in any non-system schema of the warehouse DuckDB.

## Source format

OSI ``source`` follows ``database.schema.table``. For DuckDB this is
``warehouse.<schema>.<table>``; for MotherDuck warehouses (``md:cat``)
it's ``cat.<schema>.<table>``. Other adapters (Snowflake/BigQuery)
need adapter-specific introspection that v0.1.6 doesn't ship — those
projects get a warning and an empty result.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import duckdb
import yaml

# OSI v0.1.1 schema treats the version field as a `const` — it MUST be
# this string verbatim or the schema validator rejects the file.
OSI_VERSION = "0.1.1"

SENTINEL_PREFIX = "# @generated by tycoon semantics"
SENTINEL_LINE = f"{SENTINEL_PREFIX} — remove this line to opt out of regeneration"

# Mart-prefix patterns we'll scaffold from. Anything else (staging /
# intermediate / ephemeral models) is skipped — those aren't consumer-
# facing semantic objects.
MART_PREFIXES = ("mart_", "fct_", "dim_", "obt_")


@dataclass
class ScaffoldResult:
    """Outcome of one scaffold run, used by the CLI for next-steps + tests."""

    out_path: Path
    datasets_emitted: list[str] = field(default_factory=list)
    skipped_due_to_sentinel: bool = False
    warnings: list[str] = field(default_factory=list)


def scaffold_osi(
    warehouse_db: Path,
    out_path: Path,
    project_name: str,
    *,
    force: bool = False,
) -> ScaffoldResult:
    """Read marts from ``warehouse_db`` and write an OSI YAML to ``out_path``.

    If ``out_path`` exists and the user removed the sentinel line, the
    file is preserved (return ``skipped_due_to_sentinel=True``) unless
    ``force`` is set.
    """
    if out_path.exists() and not _has_sentinel(out_path) and not force:
        return ScaffoldResult(
            out_path=out_path,
            skipped_due_to_sentinel=True,
        )

    if not warehouse_db.exists():
        return ScaffoldResult(
            out_path=out_path,
            warnings=[
                f"Warehouse not found at {warehouse_db}. "
                "Run `tycoon data transform run` first."
            ],
        )

    datasets, ds_warnings = _build_datasets(warehouse_db)
    warnings = list(ds_warnings)

    if not datasets:
        warnings.append(
            "No marts found. Looked for tables prefixed "
            + ", ".join(MART_PREFIXES)
            + f" in {warehouse_db}."
        )

    doc = _build_osi_document(project_name=project_name, datasets=datasets)
    yaml_body = yaml.dump(doc, default_flow_style=False, sort_keys=False)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(SENTINEL_LINE + "\n" + yaml_body)

    return ScaffoldResult(
        out_path=out_path,
        datasets_emitted=[d["name"] for d in datasets],
        warnings=warnings,
    )


# --------------------------------------------------------------------------
# Sentinel + introspection helpers
# --------------------------------------------------------------------------


def _has_sentinel(path: Path) -> bool:
    """True if the file's first non-blank line carries our marker."""
    try:
        with path.open() as f:
            for line in f:
                stripped = line.strip()
                if not stripped:
                    continue
                return stripped.startswith(SENTINEL_PREFIX)
    except OSError:
        return False
    return False


def _build_datasets(
    warehouse_db: Path,
) -> tuple[list[dict[str, Any]], list[str]]:
    """Introspect DuckDB and return (datasets, warnings).

    Connects read-only. Iterates schemas, finds tables matching the mart
    prefixes, pulls column names + types, classifies each column as
    measure-eligible / dimension / time-dimension.
    """
    warnings: list[str] = []
    out: list[dict[str, Any]] = []

    try:
        con = duckdb.connect(str(warehouse_db), read_only=True)
    except duckdb.Error as exc:
        return [], [f"Could not open warehouse: {exc}"]

    try:
        db_name = _resolve_db_name(con)

        rows = con.execute(
            "SELECT table_schema, table_name "
            "FROM information_schema.tables "
            "WHERE table_schema NOT IN ('information_schema', 'pg_catalog', 'main_information_schema') "
            "ORDER BY table_schema, table_name"
        ).fetchall()

        for schema, table in rows:
            if not any(table.startswith(p) for p in MART_PREFIXES):
                continue
            cols = con.execute(
                "SELECT column_name, data_type "
                "FROM information_schema.columns "
                "WHERE table_schema = ? AND table_name = ? "
                "ORDER BY ordinal_position",
                [schema, table],
            ).fetchall()
            if not cols:
                warnings.append(f"{schema}.{table}: no columns found, skipping.")
                continue
            out.append(_build_dataset_entry(db_name, schema, table, cols))
    finally:
        con.close()

    return out, warnings


def _resolve_db_name(con: duckdb.DuckDBPyConnection) -> str:
    """Return the active DuckDB catalog name (e.g. 'warehouse', 'memory')."""
    try:
        row = con.execute("SELECT current_database()").fetchone()
        return row[0] if row else "warehouse"
    except duckdb.Error:
        return "warehouse"


def _build_dataset_entry(
    db_name: str,
    schema: str,
    table: str,
    cols: list[tuple[str, str]],
) -> dict[str, Any]:
    """One Dataset dict, conformant to OSI v0.1.1's Dataset schema."""
    fields_out: list[dict[str, Any]] = []
    for col_name, data_type in cols:
        fields_out.append(_build_field_entry(col_name, data_type))

    primary_key = _guess_primary_key(table, cols)

    entry: dict[str, Any] = {
        "name": table,
        "source": f"{db_name}.{schema}.{table}",
    }
    if primary_key:
        entry["primary_key"] = primary_key
    entry["fields"] = fields_out
    return entry


def _build_field_entry(col_name: str, data_type: str) -> dict[str, Any]:
    """One Field dict, conformant to OSI v0.1.1's Field schema.

    Conservative dial (Q3): numeric columns get NO dimension attribute
    (they're measure-eligible bases for user-defined metrics). Time
    columns get ``dimension: {is_time: true}``. Everything else
    (strings, FK-shaped, booleans) gets ``dimension: {}``.
    """
    expression = {
        "dialects": [
            {"dialect": "ANSI_SQL", "expression": col_name},
        ]
    }
    field_dict: dict[str, Any] = {
        "name": col_name,
        "expression": expression,
    }
    classification = _classify_column(col_name, data_type)
    if classification == "time_dimension":
        field_dict["dimension"] = {"is_time": True}
    elif classification == "dimension":
        field_dict["dimension"] = {}
    # numeric_measure_base → omit dimension entirely
    return field_dict


# DuckDB's information_schema.columns.data_type uses canonical SQL names.
# These cover the long tail; everything not in NUMERIC or TIME falls
# through to the dimension branch.
_NUMERIC_TYPES = {
    "TINYINT", "SMALLINT", "INTEGER", "BIGINT", "HUGEINT",
    "UTINYINT", "USMALLINT", "UINTEGER", "UBIGINT",
    "FLOAT", "DOUBLE", "DECIMAL", "REAL", "NUMERIC",
}
_TIME_TYPES = {
    "DATE", "TIME", "TIMESTAMP", "TIMESTAMP_S", "TIMESTAMP_MS",
    "TIMESTAMP_NS", "TIMESTAMP WITH TIME ZONE", "TIMESTAMPTZ",
    "TIME WITH TIME ZONE",
}


def _classify_column(name: str, data_type: str) -> str:
    """Returns 'time_dimension' | 'dimension' | 'numeric_measure_base'.

    Foreign-key-shaped columns (``*_id``, ``*_key``) are dimensions —
    they're identifiers used for grouping / joining, not measure bases,
    even though they're numerically typed in most warehouses.
    """
    base_type = data_type.upper().split("(")[0].strip()

    if base_type in _TIME_TYPES:
        return "time_dimension"

    name_lower = name.lower()
    if name_lower.endswith("_id") or name_lower.endswith("_key") or name_lower == "id":
        return "dimension"

    if "DECIMAL" in base_type or "NUMERIC" in base_type:
        return "numeric_measure_base"
    if base_type in _NUMERIC_TYPES:
        return "numeric_measure_base"

    return "dimension"


def _guess_primary_key(
    table: str,
    cols: list[tuple[str, str]],
) -> list[str]:
    """Best-effort PK inference. Returns empty list when uncertain.

    Order of preference:
      1. ``id`` column (most common dim convention)
      2. ``<table_singular>_id`` column (fct_orders → orders_id, sometimes
         present alongside)
      3. Bare ``<table>_id``

    Fact tables often have composite keys; when we can't be confident we
    omit the field rather than scaffold a wrong PK.
    """
    names = [c[0] for c in cols]
    name_set = {n.lower() for n in names}

    if "id" in name_set:
        for n in names:
            if n.lower() == "id":
                return [n]

    table_lower = table.lower()
    for prefix in MART_PREFIXES:
        if table_lower.startswith(prefix):
            stem = table_lower[len(prefix):]
            for cand in (f"{stem}_id", f"{stem.rstrip('s')}_id"):
                if cand in name_set:
                    for n in names:
                        if n.lower() == cand:
                            return [n]
            break

    return []


def _build_osi_document(
    project_name: str,
    datasets: list[dict[str, Any]],
) -> dict[str, Any]:
    """Assemble the full OSI document. Validates min datasets requirement.

    OSI v0.1.1 requires at least one dataset under a SemanticModel; if
    we have none we emit a placeholder so the file still parses (the
    schema doctor will flag it).
    """
    if not datasets:
        # SemanticModel.datasets has minItems: 1. To stay schema-valid,
        # synthesize a placeholder pointing at nothing — the doctor will
        # warn the user, and they can delete it once they have marts.
        datasets = [
            {
                "name": "_placeholder",
                "source": "warehouse.main._placeholder",
                "fields": [
                    {
                        "name": "_placeholder_field",
                        "expression": {
                            "dialects": [
                                {"dialect": "ANSI_SQL", "expression": "1"}
                            ]
                        },
                    }
                ],
            }
        ]

    return {
        "version": OSI_VERSION,
        "semantic_model": [
            {
                "name": project_name,
                "description": (
                    "Generated by tycoon from dbt marts. Edit metrics + "
                    "relationships by hand; tycoon will preserve them on "
                    "regenerate as long as this file's first-line sentinel "
                    "stays intact."
                ),
                "datasets": datasets,
                "metrics": [],
                "relationships": [],
            }
        ],
    }


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------


def osi_schema_path() -> Path:
    """Path to the vendored OSI v0.1.1 JSON Schema file."""
    return Path(__file__).parent / "schemas" / "osi-v0.1.1.schema.json"


def validate_osi_yaml(yaml_path: Path) -> list[str]:
    """Validate a YAML file against the vendored OSI v0.1.1 schema.

    Returns a list of human-readable error messages. Empty list = valid.
    """
    import json

    from jsonschema import Draft202012Validator

    if not yaml_path.exists():
        return [f"OSI file not found: {yaml_path}"]

    try:
        body = yaml.safe_load(yaml_path.read_text())
    except yaml.YAMLError as exc:
        return [f"YAML parse error: {exc}"]

    schema = json.loads(osi_schema_path().read_text())
    validator = Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(body), key=lambda e: e.path)

    out: list[str] = []
    for err in errors:
        path = "/".join(str(p) for p in err.absolute_path) or "<root>"
        out.append(f"{path}: {err.message}")
    return out
