"""The spike fixture bench: every catalog shape the test suite already trusts.

Not a test — the shared input list for `spike_contact_sheet.py` (the v4 BEFORE
picture) and `spike_lattice.py` (the v5 blocks-first footprint). The synthetic
families are harvested verbatim from the shapes the suite sweeps:

  tests/sim/test_generator_properties.py  flat grids, chain, diamond, skewed
                                          fans, long edges, cycles, 8 random
                                          DAGs, the 500-object cap, star
                                          schemas with sibling blocks, 4 sized
                                          catalogs with 2x2 footprints
  tests/sim/test_layout_plan.py           the chain+orphan, the banding
                                          fixture, the sibling block, the
                                          12-destination sprawl case, the
                                          2x2-footprint case, the empty catalog

plus the two real sources in the repo: `demo.duckdb` and `demo-tycoon/` (the
latter is generated by `scripts/make_demo_tycoon.py` and is skipped, named, if
it is not there). NOTHING here reads `~/clients/dogfood` — that path does not
exist in this checkout and no test or spike may depend on it.

The names are the ones the tests use, so a defect seen in a render can be
reproduced by running the family it came from.
"""

from __future__ import annotations

import dataclasses
import random
from collections.abc import Callable
from pathlib import Path

from dbtycoon.catalog.models import CatalogObject, Edge, PipelineContext

REPO = Path(__file__).resolve().parents[1]


def shuffled(ctx: PipelineContext, seed: int) -> PipelineContext:
    """The same catalog with `objects` and `edges` permuted, nothing else.

    A planner that reads its inputs in ARRIVAL order rather than sorted order
    produces a different city from this and an identical one from every other
    check, which is why both spikes fingerprint the shuffled variant. Shared
    here so the v4 and v5 harnesses cannot drift on what "shuffled" means.
    """
    rng = random.Random(seed)
    objects = list(ctx.objects)
    edges = list(ctx.edges)
    rng.shuffle(objects)
    rng.shuffle(edges)
    return dataclasses.replace(ctx, objects=tuple(objects), edges=tuple(edges))


def _ctx(objects, edges=()) -> PipelineContext:
    return PipelineContext("demo", tuple(objects), tuple(edges))


def _obj(schema: str, name: str) -> CatalogObject:
    return CatalogObject(schema, name, "table", 0)


def _catalog(schema_sizes, edges=()) -> PipelineContext:
    objects: list[CatalogObject] = []
    for schema, n in schema_sizes:
        objects.extend(_obj(schema, f"t{i}") for i in range(n))
    return _ctx(objects, edges)


# --------------------------------------------------------------------------
# The families, in the order the property sweep declares them.
# --------------------------------------------------------------------------


def _flat(n_schemas: int, size: int) -> PipelineContext:
    return _catalog([(f"s{i}", size) for i in range(n_schemas)])


def _chain() -> PipelineContext:
    return _catalog(
        [("raw", 1), ("staging", 1), ("marts", 1)],
        [Edge("raw.t0", "staging.t0"), Edge("staging.t0", "marts.t0")],
    )


def _diamond() -> PipelineContext:
    return _ctx(
        [_obj("a", "src"), _obj("b", "l"), _obj("b", "r"), _obj("c", "sink")],
        [Edge("a.src", "b.l"), Edge("a.src", "b.r"), Edge("b.l", "c.sink"), Edge("b.r", "c.sink")],
    )


def _fan_in(n: int) -> PipelineContext:
    return _ctx(
        [_obj("s", f"t{i}") for i in range(n)] + [_obj("m", "sink")],
        [Edge(f"s.t{i}", "m.sink") for i in range(n)],
    )


def _fan_out(n: int) -> PipelineContext:
    return _ctx(
        [_obj("s", "src")] + [_obj("m", f"t{i}") for i in range(n)],
        [Edge("s.src", f"m.t{i}") for i in range(n)],
    )


def _long_edge() -> PipelineContext:
    objects = [_obj(f"s{i}", f"t{j}") for i in range(5) for j in range(4)]
    edges = [Edge(f"s{i}.t{j}", f"s{i + 1}.t{j}") for i in range(4) for j in range(4)]
    edges.append(Edge("s0.t0", "s4.t3"))
    return _ctx(objects, edges)


def _two_cycle() -> PipelineContext:
    return _ctx(
        [_obj("a", "x"), _obj("a", "y"), _obj("b", "down")],
        [Edge("a.x", "a.y"), Edge("a.y", "a.x"), Edge("a.y", "b.down")],
    )


def _random(seed: int) -> PipelineContext:
    rng = random.Random(seed)
    n = rng.randint(5, 40)
    objects = [_obj(f"s{i % 5}", f"t{i}") for i in range(n)]
    keys = [o.key for o in objects]
    edges = set()
    for _ in range(rng.randint(0, n * 2)):
        a, b = rng.sample(range(n), 2)
        if a < b:
            edges.add(Edge(keys[a], keys[b]))
    return _ctx(objects, sorted(edges, key=lambda e: (e.src, e.dst)))


def _cap_500() -> PipelineContext:
    objects = [_obj(f"s{i % 10}", f"t{i}") for i in range(500)]
    keys = [o.key for o in objects]
    rng = random.Random(42)
    edges = {Edge(keys[i], keys[i + 10]) for i in range(0, 480, 3)}
    for _ in range(200):
        a, b = rng.sample(range(500), 2)
        if a < b:
            edges.add(Edge(keys[a], keys[b]))
    return _ctx(objects, sorted(edges, key=lambda e: (e.src, e.dst)))


def _star_blocks() -> PipelineContext:
    objects = (
        [_obj("stg", "a"), _obj("stg", "b"), _obj("stg", "c")]
        + [_obj("mart", f"m{i}") for i in range(6)]
        + [_obj("mart", "solo1"), _obj("mart", "solo2")]
    )
    edges = [Edge(f"stg.{s}", f"mart.m{i}") for s in ("a", "b") for i in range(6)] + [
        Edge("stg.a", "mart.solo1"),
        Edge("stg.c", "mart.solo2"),
    ]
    return _ctx(objects, edges)


def _sized(seed: int) -> PipelineContext:
    rng = random.Random(seed)
    n = rng.randint(12, 32)
    objects = [CatalogObject(f"s{i % 4}", f"t{i}", "table", rng.randint(1, 10_000)) for i in range(n)]
    keys = [o.key for o in objects]
    edges = set()
    for _ in range(rng.randint(4, n * 2)):
        a, b = rng.sample(range(n), 2)
        if a < b:
            edges.add(Edge(keys[a], keys[b]))
    return _ctx(objects, sorted(edges, key=lambda e: (e.src, e.dst)))


# --- the crafted plan fixtures (tests/sim/test_layout_plan.py) -------------


def _chain_orphan() -> PipelineContext:
    return _ctx(
        [_obj("raw", "a"), _obj("staging", "b"), _obj("marts", "c"), _obj("scratch", "x")],
        [Edge("raw.a", "staging.b"), Edge("staging.b", "marts.c")],
    )


def _bands() -> PipelineContext:
    return _ctx(
        [_obj("apple", f"a{i}") for i in range(3)]
        + [_obj("zebra", f"z{i}") for i in range(3)]
        + [_obj("m1", "d1"), _obj("m2", "d2")],
        [
            Edge("apple.a0", "m1.d1"),
            Edge("apple.a2", "m1.d1"),
            Edge("zebra.z0", "m1.d1"),
            Edge("apple.a1", "m2.d2"),
            Edge("zebra.z1", "m2.d2"),
            Edge("zebra.z2", "m2.d2"),
        ],
    )


def _sibling_block() -> PipelineContext:
    return _ctx(
        [_obj("stg", "a"), _obj("stg", "b")] + [_obj("mart", f"m{i}") for i in range(3)] + [_obj("mart", "other")],
        [Edge(f"stg.{s}", f"mart.m{i}") for s in ("a", "b") for i in range(3)] + [Edge("stg.a", "mart.other")],
    )


def _sprawl_12() -> PipelineContext:
    return _ctx(
        [_obj("a", "src")] + [_obj(f"s{i}", f"d{i}") for i in range(12)],
        [Edge("a.src", f"s{i}.d{i}") for i in range(12)],
    )


def _big_2x2() -> PipelineContext:
    objects = [CatalogObject("s", f"t{i}", "table", 10 + i) for i in range(9)] + [
        CatalogObject("s", "hub", "table", 90_000),
        CatalogObject("m", "sink", "table", 0),
    ]
    return _ctx(objects, [Edge("s.hub", "m.sink"), Edge("s.t0", "m.sink")])


def _empty() -> PipelineContext:
    return _ctx([])


def _dotted_tie() -> PipelineContext:
    """Schemas whose MEMBER KEYS do not sort the way their names do.

    Every other fixture on this bench hides two whole classes of ordering bug.
    A key is `schema.name`, so the schema prefix decides every comparison
    before it ever reaches a member name: a band tiebreak that reads a member
    key is then indistinguishable from one that reads the schema, AND
    indistinguishable from one that reads whichever member happened to arrive
    first. That is why round 1's `members[0]` mutant survived. A dot inside
    the schema name breaks the prefix, and the two pairs here break it in the
    two different directions the tiebreak can be wrong in:

      a / a.y     every member of `a` sorts AFTER `a.y.*`, so ordering by
                  member key puts a.y first and ordering by SCHEMA NAME puts
                  a first — the fixture that can see that difference at all.
      c / c.y     `c` straddles it (`c.x0` before `c.y.*`, `c.z0` after), so
                  taking an ARBITRARY member instead of the minimum flips the
                  band order with the input order, and the shuffled-input
                  check finally has something to kill.

    All four are orphans, which is what makes their band ranks TIE and hands
    the decision to the tiebreak; with no edges every object is depth 0, so
    this is also the all-industrial catalog.
    """
    return _ctx(
        [_obj("a", f"z{i}") for i in range(3)]
        + [_obj("a.y", f"b{i}") for i in range(2)]
        + [_obj("c", "x0"), _obj("c", "z0")]
        + [_obj("c.y", f"b{i}") for i in range(2)]
    )


SYNTHETIC: list[tuple[str, Callable[[], PipelineContext]]] = (
    [(f"flat-{n}x{s}", (lambda n=n, s=s: _flat(n, s))) for n in (1, 3, 7) for s in (1, 4, 9)]
    + [
        ("chain", _chain),
        ("diamond", _diamond),
        ("fan-in-20", lambda: _fan_in(20)),
        ("fan-out-20", lambda: _fan_out(20)),
        ("long-edge", _long_edge),
        ("two-cycle", _two_cycle),
    ]
    + [(f"random-{s}", (lambda s=s: _random(s))) for s in range(8)]
    + [
        ("cap-500", _cap_500),
        ("star-blocks", _star_blocks),
    ]
    + [(f"sized-{s}", (lambda s=s: _sized(s))) for s in range(4)]
    + [
        ("chain-orphan", _chain_orphan),
        ("bands", _bands),
        ("sibling-block", _sibling_block),
        ("sprawl-12", _sprawl_12),
        ("big-2x2", _big_2x2),
        ("empty", _empty),
        ("dotted-tie", _dotted_tie),
    ]
)

# The two real sources that live in this checkout. Never dogfood.
REAL_SOURCES: list[tuple[str, Path]] = [
    ("demo.duckdb", REPO / "demo.duckdb"),
    ("demo-tycoon", REPO / "demo-tycoon"),
]


def load_fixtures(only: str | None = None) -> list[tuple[str, PipelineContext]]:
    """Every fixture as `(name, context)`, synthetic first then the real ones.

    A real source that is absent is reported on stdout and skipped rather than
    silently dropped — an absent input must stay NAMED. `only` filters by exact
    name (the detail modes take one).
    """
    from dbtycoon.catalog.errors import CatalogError
    from dbtycoon.catalog.loader import load_context

    out: list[tuple[str, PipelineContext]] = []
    for name, build in SYNTHETIC:
        if only is None or name == only:
            out.append((name, build()))
    for name, path in REAL_SOURCES:
        if only is not None and name != only:
            continue
        if not path.exists():
            print(f"  (skipped {name}: {path} is not present)")
            continue
        try:
            out.append((name, load_context(path)))
        except CatalogError as exc:  # pragma: no cover - spike-only path
            print(f"  (skipped {name}: {exc})")
    return out
