"""tycoon semantics — emit + validate Open Semantic Interchange YAML.

Two subcommands:

* ``scaffold`` — read marts from the warehouse, write
  ``dbt_project/semantic/osi.yaml``. Conservative dial: scaffold
  datasets + dimensional fields only, no metrics.
* ``doctor`` — validate the generated YAML against the vendored OSI
  v0.1.1 JSON Schema. Hard exit code (CI-friendly).

dbt MetricFlow remains the source of truth; OSI is a portable
*published view* downstream consumers (Snowflake Cortex, ThoughtSpot,
RelationalAI, ...) can ingest directly.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer

from tycoon.config import config
from tycoon.scaffolding.osi_generator import (
    scaffold_osi,
    validate_osi_yaml,
)
from tycoon.utils.console import error, header, info, success, warn

app = typer.Typer(
    help="Emit + validate Open Semantic Interchange (OSI) YAML from dbt marts.",
    no_args_is_help=True,
)


def _require_project() -> None:
    if not config.has_project_file:
        error(
            "No tycoon.yml found. Run [bold]tycoon init[/bold] first, "
            "or cd into an existing tycoon project."
        )
        raise typer.Exit(1)


def _default_out_path() -> Path:
    """Project-level OSI file location (Q2 decision — issue #28)."""
    return config.dbt_project_dir / "semantic" / "osi.yaml"


@app.command()
def scaffold(
    out: Optional[Path] = typer.Option(
        None,
        "--out",
        "-o",
        help="Output path. Default: <dbt_project_dir>/semantic/osi.yaml.",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help=(
            "Overwrite a file whose `# @generated by tycoon semantics` "
            "sentinel was removed. Without --force, such files are skipped "
            "with a warning."
        ),
    ),
) -> None:
    """Generate an OSI v0.1.1 YAML from the warehouse's marts.

    Looks for tables prefixed `mart_`, `fct_`, `dim_`, `obt_` in any
    non-system schema of the warehouse DuckDB. Writes one project-level
    file with all datasets + dimensional fields. Metrics + relationships
    are left empty by design (Conservative dial — issue #28 Q3) so the
    user can fill them in by hand without fighting bad guesses.
    """
    _require_project()
    header("OSI semantic-layer scaffold")

    out_path = (out.expanduser().resolve() if out else _default_out_path())

    project = config.project
    project_name = project.name if project else config.root.name

    result = scaffold_osi(
        warehouse_db=config.local_db,
        out_path=out_path,
        project_name=project_name,
        force=force,
    )

    if result.skipped_due_to_sentinel:
        warn(
            f"Skipped {result.out_path} — sentinel line removed. "
            "Run with [bold]--force[/bold] to overwrite hand-edited content."
        )
        raise typer.Exit(0)

    for w in result.warnings:
        warn(w)

    if result.datasets_emitted:
        success(
            f"Wrote {result.out_path} — "
            f"{len(result.datasets_emitted)} dataset(s): "
            + ", ".join(result.datasets_emitted)
        )
        info(
            "Next: edit `metrics:` and `relationships:` by hand, then "
            "[bold]tycoon semantics doctor[/bold] to validate."
        )
    else:
        info(
            f"Wrote {result.out_path} (no marts found — placeholder "
            "dataset emitted to keep the file schema-valid)."
        )


@app.command()
def doctor(
    path: Optional[Path] = typer.Option(
        None,
        "--path",
        help="OSI YAML to validate. Default: <dbt_project_dir>/semantic/osi.yaml.",
    ),
) -> None:
    """Validate an OSI YAML against the vendored v0.1.1 JSON Schema.

    Exits 0 on schema-valid, 1 on any validation error. Uses a vendored
    schema file — no network access needed.
    """
    _require_project()
    header("OSI semantic-layer doctor")

    osi_path = (path.expanduser().resolve() if path else _default_out_path())

    if not osi_path.exists():
        error(
            f"OSI YAML not found at {osi_path}. "
            "Run [bold]tycoon semantics scaffold[/bold] first."
        )
        raise typer.Exit(1)

    errors = validate_osi_yaml(osi_path)
    if not errors:
        success(f"{osi_path} is valid OSI v0.1.1.")
        raise typer.Exit(0)

    error(f"{osi_path} has {len(errors)} validation error(s):")
    for e in errors:
        info(f"  • {e}")
    raise typer.Exit(1)


def run_osi_check(path: Optional[Path] = None) -> int:
    """Shared check used by `tycoon doctor`. Returns 0 if valid or skipped, 1 if invalid.

    Skips silently when no OSI file exists — OSI is opt-in per the v0.1.6
    design (issue #28 Q6). Only flags when a file exists *and* fails.
    """
    osi_path = (path.expanduser().resolve() if path else _default_out_path())
    if not osi_path.exists():
        info("OSI: no semantic/osi.yaml present (opt-in via `tycoon semantics scaffold`).")
        return 0

    errors = validate_osi_yaml(osi_path)
    if not errors:
        success(f"OSI: {osi_path} is valid OSI v0.1.1.")
        return 0

    warn(f"OSI: {osi_path} has {len(errors)} validation error(s) — run `tycoon semantics doctor` for details.")
    return 1
